[package]
name = "biggaboy212/pact"
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["init.luau", "lib/"]
exclude = ["aftman.toml", "pipeline", "debug", ".vscode", ".globals", ".layoutignore", "layout.py", "project_context.txt"]

[dependencies]